---
- hosts: target1
  tasks:
    - name: install java
      yum:
        name: java-1.8.0
        state: latest

    - name: create a dir
      file:
        path: /tmp/gamefolder
        state: directory

    - name: download maven artifact from nexus
      maven_artifact:
        group_id: be.cegeka
        artifact_id: gameoflife
        version: 0.0.2
        extension: war
        username: admin
        password: "{{ pass }}"
        repository_url: http://3.16.42.191:8081/nexus/content/repositories/releases/
        dest: /tmp/gamefolder/gameoflife.war

    - name: start your application
      shell: nohup java -jar gameoflife.war &
      args:
        chdir: /tmp/gamefolder
